//GLOBAL
export const GLOBAL_ERROR = "@GLOBAL/ERROR";
export const GLOBAL_ERROR_CLEAR = "@GLOBAL/ERROR_CLEAR";
export const GLOBAL_START_LOADING = "@GLOBAL/START_LOADING";
export const GLOBAL_STOP_LOADING = "@GLOBAL/STOP_LOADING";

export const GET_CEP_INFO_REQUEST = '@UTILS/GET_CEP_INFO_REQUEST'
export const GET_CEP_INFO_SUCCESS = '@UTILS/GET_CEP_INFO_SUCCESS'
export const GET_STATES_REQUEST = '@UTILS/GET_STATES_REQUEST'
export const GET_STATES_SUCCESS = '@UTILS/GET_STATES_SUCCESS'
export const GET_CITY_LIST_REQUEST = '@UTILS/GET_CITY_LIST_REQUEST'
export const GET_CITY_LIST_SUCCESS = '@UTILS/GET_CITY_LIST_SUCCESS'

//AUTH
export const AUTH_START_LOADING = "@AUTH/AUTH_START_LOADING";
export const AUTH_STOP_LOADING = "@AUTH/AUTH_STOP_LOADING";
export const AUTH_START_LOADING_CHANGE_CHURCH = "@AUTH/START_LOADING_CHANGE_CHURCH";
export const AUTH_STOP_LOADING_CHANGE_CHURCH = "@AUTH/STOP_LOADING_CHANGE_CHURCH";
export const LOGIN_REQUEST = "@AUTH/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "@AUTH/LOGIN_SUCCESS";
export const UPDATE_PASSWORD_FIRST_LOGIN_REQUEST = "@AUTH/UPDATE_PASSWORD_FIRST_REQUEST";
export const UPDATE_PASSWORD_FIRST_LOGIN_SUCCESS = "@AUTH/UPDATE_PASSWORD_FIRST_SUCCESS";

export const CHANGE_CHURCH_REQUEST = "@AUTH/CHANGE_CHURCH_REQUEST";
export const CHANGE_CHURCH_SUCCESS = "@AUTH/CHANGE_CHURCH_SUCCESS";

//USERS
export const USER_LIST_REQUEST = "@USERS/USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "@USERS/USER_LIST_SUCCESS";
export const USER_PREPARE_SAVE_REQUEST = "@USERS/PREPARE_SAVE_REQUEST";
export const USER_PREPARE_SAVE_SUCCESS = "@USERS/PREPARE_SAVE_SUCCESS";
export const USER_PREPARE_EDIT_REQUEST = "@USERS/PREPARE_EDIT_REQUEST";
export const USER_PREPARE_EDIT_SUCCESS = "@USERS/PREPARE_EDIT_SUCCESS";
export const USER_SAVE_REQUEST = "@USERS/SAVE_REQUEST";
export const USER_SAVE_SUCCESS = "@USERS/SAVE_SUCCESS";
export const USER_UPDATE_REQUEST = "@USERS/UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "@USERS/UPDATE_SUCCESS";
export const USER_DELETE_REQUEST = "@USERS/DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "@USERS/DELETE_SUCCESS";

//USERS
export const CHURCH_LIST_REQUEST = "@CHURCHES/CHURCH_LIST_REQUEST";
export const CHURCH_LIST_SUCCESS = "@CHURCHES/CHURCH_LIST_SUCCESS";
export const CHURCH_PREPARE_SAVE_REQUEST = "@CHURCHES/PREPARE_SAVE_REQUEST";
export const CHURCH_PREPARE_SAVE_SUCCESS = "@CHURCHES/PREPARE_SAVE_SUCCESS";
export const CHURCH_PREPARE_EDIT_REQUEST = "@CHURCHES/PREPARE_EDIT_REQUEST";
export const CHURCH_PREPARE_EDIT_SUCCESS = "@CHURCHES/PREPARE_EDIT_SUCCESS";
export const CHURCH_SAVE_REQUEST = "@CHURCHES/SAVE_REQUEST";
export const CHURCH_SAVE_SUCCESS = "@CHURCHES/SAVE_SUCCESS";
export const CHURCH_UPDATE_REQUEST = "@CHURCHES/UPDATE_REQUEST";
export const CHURCH_UPDATE_SUCCESS = "@CHURCHES/UPDATE_SUCCESS";
export const CHURCH_DELETE_REQUEST = "@CHURCHES/DELETE_REQUEST";
export const CHURCH_DELETE_SUCCESS = "@CHURCHES/DELETE_SUCCESS";

//CHURCH JOBS
export const CHURCH_JOB_LIST_REQUEST = "@CHURCH_JOBS/CHURCH_JOB_LIST_REQUEST";
export const CHURCH_JOB_LIST_SUCCESS = "@CHURCH_JOBS/CHURCH_JOB_LIST_SUCCESS";
export const CHURCH_JOB_PREPARE_SAVE_REQUEST = "@CHURCH_JOBS/PREPARE_SAVE_REQUEST";
export const CHURCH_JOB_PREPARE_SAVE_SUCCESS = "@CHURCH_JOBS/PREPARE_SAVE_SUCCESS";
export const CHURCH_JOB_PREPARE_EDIT_REQUEST = "@CHURCH_JOBS/PREPARE_EDIT_REQUEST";
export const CHURCH_JOB_PREPARE_EDIT_SUCCESS = "@CHURCH_JOBS/PREPARE_EDIT_SUCCESS";
export const CHURCH_JOB_SAVE_REQUEST = "@CHURCH_JOBS/SAVE_REQUEST";
export const CHURCH_JOB_SAVE_SUCCESS = "@CHURCH_JOBS/SAVE_SUCCESS";
export const CHURCH_JOB_UPDATE_REQUEST = "@CHURCH_JOBS/UPDATE_REQUEST";
export const CHURCH_JOB_UPDATE_SUCCESS = "@CHURCH_JOBS/UPDATE_SUCCESS";
export const CHURCH_JOB_DELETE_REQUEST = "@CHURCH_JOBS/DELETE_REQUEST";
export const CHURCH_JOB_DELETE_SUCCESS = "@CHURCH_JOBS/DELETE_SUCCESS";

//CHURCH JOBS
export const ROLE_LIST_REQUEST = "@ROLES/ROLE_LIST_REQUEST";
export const ROLE_LIST_SUCCESS = "@ROLES/ROLE_LIST_SUCCESS";
export const ROLE_PREPARE_SAVE_REQUEST = "@ROLES/PREPARE_SAVE_REQUEST";
export const ROLE_PREPARE_SAVE_SUCCESS = "@ROLES/PREPARE_SAVE_SUCCESS";
export const ROLE_PREPARE_EDIT_REQUEST = "@ROLES/PREPARE_EDIT_REQUEST";
export const ROLE_PREPARE_EDIT_SUCCESS = "@ROLES/PREPARE_EDIT_SUCCESS";
export const ROLE_SAVE_REQUEST = "@ROLES/SAVE_REQUEST";
export const ROLE_SAVE_SUCCESS = "@ROLES/SAVE_SUCCESS";
export const ROLE_UPDATE_REQUEST = "@ROLES/UPDATE_REQUEST";
export const ROLE_UPDATE_SUCCESS = "@ROLES/UPDATE_SUCCESS";
export const ROLE_DELETE_REQUEST = "@ROLES/DELETE_REQUEST";
export const ROLE_DELETE_SUCCESS = "@ROLES/DELETE_SUCCESS";